# Generated by Django 2.2.1 on 2019-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='text',
            field=models.TextField(verbose_name='经营范围'),
        ),
    ]
