# Generated by Django 2.2.1 on 2019-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191209_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='餐馆名')),
                ('money', models.CharField(max_length=32, verbose_name='平均消费')),
                ('addr', models.CharField(max_length=32, verbose_name='地址')),
                ('food_type', models.CharField(max_length=32, verbose_name='类型')),
            ],
        ),
    ]
