# Generated by Django 2.2.1 on 2019-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='资质')),
            ],
        ),
    ]
