# Generated by Django 2.2.1 on 2019-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_sort_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sort_num',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
