# Generated by Django 2.2.1 on 2019-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20191212_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sort_num',
        ),
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='显示顺序'),
        ),
    ]
